name: lookyitsmrhyde
favicon: null
layout_spectrum: 0.3453004201874137
typography_spectrum: 0.7578997833188623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfbf9'
    - '#221533'
    - '#dfdad6'
    - '#c5bab6'
    - '#8b7e7d'
  brandStrength: 0.998205590993166
  lightness: 0.3100978920701891
  saturation: 0.5366548430174589
  rhythmicContrast: 0.321351055521518
purpose: []
